{ pkgs, ... }:
{
  imports = [
    # `hardware-configuration.nix` is generated by NixOS automatically.
    # Generally. tha path of this nix file is fixed.
    # So DON NOT modifiy it if unnecessary.
    /etc/nixos/hardware-configuration.nix

    ./system
  ];

  system.stateVersion = "24.05";

  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  # [garbage collection]
  # ----------------------------------------------------
  # do garbage collection weekly to keep disk usage low
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 1w";
  };

  # [optimise storage]
  # --------------------
  # you can also optimise the store manually via:
  #    nix-store --optimise
  # https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-auto-optimise-store
  nix.settings.auto-optimise-store = true;

  # todo: t
  nixpkgs.config.allowUnfree = true;

  programs.clash-verge = {
    enable = true;
    package = pkgs.clash-verge-rev;
  };
}
